# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O4eNgM-TG1gSRM2a0NAmppuTe8qtRBgx
"""

from nodal_analysis.well.well_model import Well
from nodal_analysis.inv_well.inv_well_model import Inverted_well

def run_nodal_solver(coef_productivity, p_w, p_e, time):
    well = Well(coef_productivity, p_w, p_e, time)
    inv_well = Inverted_well(coef_productivity, p_w, time)
    return well, inv_well