# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O4eNgM-TG1gSRM2a0NAmppuTe8qtRBgx
"""

class Well:

  def __init__(self, prod_index, reservoir_press, q = 0):
    self.prod_index = prod_index
    self.reservoir_press = reservoir_press
    self.q = q
    self.Q = q * 31
    self.nacop = 0

  def get_q(self, well_press):
    self.q = self.prod_index * (self.reservoir_press - well_press)
    self.Q = self.q * 31
    self.nacop = self.nacop + self.q
    return self.q

well = Well(10, 300)

